### ISSUE TITLE
webui项目可以用了吗？？那个tisan-web-ide不能调用ＲＰＣ

### ISSUE THREAD

**Issue by lijian405** [ruizeng/pando-cloud#38]

**Comment by ruizeng** [comment]
你好,tisan-web-ide项目是基于此项目开发的第三方组件，和pando cloud本身并没有直接关系，我也无法回答里面的问题。目前可能tisan-web-ide的开发者没有维护了，不过关于pando cloud的任何疑问我都会解答，谢谢。
