### ISSUE TITLE
设备一段时间就会掉线，应该从哪里入手查问题

### ISSUE THREAD

**Issue by lijian405** [ruizeng/pando-cloud#39]
不定时掉线，但再重新上电又可以连接，会不会跟嵌入式的代码有关系
另外，如何查看ＰandoCloud的日志信息

**Comment by Zhang-Jia** [comment]
@lijian405,你好加我qq讨论一下501922207

**Comment by coolcm** [comment]
还有人在弄这个pandocloud吗
