### ISSUE TITLE
对应的应用服务器可以开源吗？

### ISSUE THREAD

**Issue by 0uyangsheng** [ruizeng/pando-cloud#40]
看了下free-iot Android端源码，其中：
private static String API_SERVER_URL = "https://api.pandocloud.com" 打不开了。也就是说freeiot没法用了。

能否开源 free-iot对应的应用服务器？ @ruizeng

**Comment by ruizeng** [comment]
我们提供的云服务已经不维护了，本项目仅限学习交流用。

**Comment by 0uyangsheng** [comment]
可以私下发给我吗，往您 razr.china@gmail.com 发了邮件。
