### ISSUE TITLE
设备接入流程

### ISSUE THREAD

**Issue by lawrence-peng** [ruizeng/pando-cloud#41]
* 能不能提供一个设备接入 pando 物联网平台详细方案，接入流程和接入协议具体案例。
* 设备代理(网关)的实现是在硬件自己本身去实现吗？如，现很热门共享自行车的解决方案，如果用  pando 物联网平台来实现， 设备代理(网关) 的实现 在那个部分呢？

望解惑，在此谢过了！

**Comment by ruizeng** [comment]
你好，在这个group中应该有你想要的方案，但是项目都长时间没维护了，仅供参考。https://github.com/PandoCloud
