### ISSUE TITLE
提个关于pdcfg的问题

### ISSUE THREAD

**Issue by yaw123** [ruizeng/pando-cloud#43]
pdcfg配置工具是使用命令行来添加数据的；
现在我做了一个后台，直接表单提交，但是数据之间没有关系，然后使用$GOPATH/bin/device -productkey=。。。。    **我的productkey是用sha256（base64）加密的**  
这里出现这样的问题
[request url]:https://localhost/v1/devices/registration
[request content]:{"product_key":"da52d3b0b2ca6e23267a710d2720f11ed8b5115723caa20b45fd578cfad5f5ee","device_code":"ffe34e","version":"version"}
[request type]:POST
[request head]:map[]
[respons body]:{"code":10001,"message":"record not found"}
问题一：     这是因为我productkey的加密问题   还是pdcfg工具内部数据间有关系；如果是这样的话，那我想写一个后台提交的数据添加工具该怎么办，可以提供一个思路？ 谢谢

这里我是怀疑pando中里面有处理的，所以我修改了后台，
详情：建了一个文件夹add，有一个add.go文件，就和pdcfg包里vendor.go文件一样导入包，
 建了一个Addvendor(vendor_name ,description string) error函数，调用了server包里的RPCCallByName函数：         代码如下
package add
import (
	"fmt"
	"github.com/PandoCloud/pando-cloud/pkg/models"
	"github.com/PandoCloud/pando-cloud/pkg/server"
	"strings"
)
func AddVendor(vendor_name string,description string) error{
	args := models.Vendor{}
	args.VendorName =  strings.Replace(vendor_name, "\n", "", -1)
	args.VendorDescription =  strings.Replace(description, "\n", "", -1)
	reply := &models.Vendor{}
	err := server.RPCCallByName("registry","Registry.SaveVendor",&args,reply)
	if err != nil{
		return err
	}
	fmt.Println("=======> vendor created successfully:")
	return err
}
在我的添加vendor表的页面添加函数里调用了err := add.AddVendor(vendor_name,description) 出现
the request url is  /product/add
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] Handler crashed with error runtime error: invalid memory address or nil pointer dereference
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/runtime/asm_amd64.s:509
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/runtime/panic.go:491
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/runtime/panic.go:63
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/runtime/signal_unix.go:367
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /golang/src/github.com/Sirupsen/logrus/entry.go:144
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /golang/src/github.com/PandoCloud/pando-cloud/pkg/server/utils.go:10
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /golang/src/github.com/PandoCloud/pando-cloud/pkg/server/server.go:167
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /golang/src/pandobackstage/models/model.go:527
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /golang/src/pandobackstage/controllers/product.go:50
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/runtime/asm_amd64.s:509
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/reflect/value.go:434
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/reflect/value.go:302
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /golang/src/github.com/astaxie/beego/router.go:847
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/net/http/server.go:2619
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/net/http/server.go:1801
2018/02/06 15:14:27.609 [C] [asm_amd64.s:509] /usr/local/go/src/runtime/asm_amd64.s:2337
问题二： 为什么不行呢，pdcfg包也是这样的

**Comment by ruizeng** [comment]
你的key的生成是自己做的生成算法么？可能是解出来的id不存在

**Comment by yaw123** [comment]
是的，那productkey加密算法是怎样的呢，err := client.Call(serverMethod, args, reply)查到这里还是没找到
