### ISSUE TITLE
接着上个问题提出的想法，请衡量是否可行

### ISSUE THREAD

**Issue by yaw123** [ruizeng/pando-cloud#44]
在数据提交时，使用go调用Linux的外部命令来执行pdcfg，是否可以达到同样的结果？

数据提交保存到一个文件里，调用外部命令时，逐行读取

**Comment by ruizeng** [comment]
利用UNIX管道的原理是可以实现的，但是没有必要。你还是用自己参考pdcfg来修改比较好
