### ISSUE TITLE
物联网平台咋不维护了？

### ISSUE THREAD

**Issue by wangcmin2064** [ruizeng/pando-cloud#45]
我也有开源物联网平台的想法，以前也做过商用的。不知道你为啥不往下做了，可否方便说说？

**Comment by ruizeng** [comment]
你好，此平台不维护了，仅限学习交流

wangcmin2064 <notifications@github.com> 于2018年10月21日周日 上午9:29写道：

**Comment by ruizeng** [comment]
@wangcmin2064 目前不再做相关方向，所以没维护了
